import Head from 'next/head';
import Curve from '@/components/Layout/Curve';
import Parallax from '@/components/Parallax/parallax';
import SampleVideo from '@/components/SampleVideo/sample-video';
import OurBusinesses from '@/cms-components/OurBusinesses/OurBusinesses';

import {
	animate,
	motion,
	useScroll,
	useSpring,
	useTransform,
} from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';
import Card from '@/components/card/card';
import Button from '@/components/button/button';
import PageCTA from '@/cms-components/PageCTA/PageCTA';
import PageTitle from '@/cms-components/PageTitle/PageTitle';
import div from '@/components/single-parallax/single-parallax';
import { useDimensions } from '@/hooks/use-dimension';
import useAnim from '@/hooks/use-anim';
import { pageTranslate } from '@/hooks/pageAnim';
import TextGradient from '@/cms-components/TextGradient/TextGradient';
import SingleParallax from '@/components/single-parallax/single-parallax';
import Image from 'next/image';
import ParallaxGrid from '@/cms-components/ParallaxGrid/ParallaxGrid';
import ColumnSection from '@/cms-components/ColumnSection/ColumnSection';
import { AspectRatio } from '@chakra-ui/react';
import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';

export default function CSR() {
	const images = [
		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',

		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',

		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',

		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',
		'/images/Homepage-1/1.png',
	];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageTitle
					title='Corporate'
					split='Social Responsibility'
					horizontal='center'
				/>

				<FullPageBanner />

				<TextGradient
					anim={{ ...useAnim(pageTranslate(2)) }}
					classes='heading-2'
					paddingBottom={'unset'}
					paragraph={
						"More than a slogan, it's a calling to our better selves. It's a credo rooted in hope and action."
					}
				/>

				<ColumnSection>
					<>
						<p>
							As a company, San Miguel Corporation invests in social projects
							not only because it makes good business sense, but because we
							believe the private sector needs to do its part. If the cities and
							communities we serve are thriving, San Miguel will thrive too.
						</p>
					</>
					<>
						<AspectRatio maxW='560px' ratio={1}>
							<img src='/images/Homepage-1/1.png'></img>
						</AspectRatio>
					</>
				</ColumnSection>

				<ParallaxGrid images={images} anim={useAnim(pageTranslate(1))}>
					<h2 className='heading-3'>The world we want</h2>
					<p>
						There’s a reason why poverty and income inequality are called wicked
						problems, and even a company as large and as diverse as San Miguel
						can’t solve it alone.
					</p>
					<p>
						It takes everyone to come together to think about how we might solve
						these problems together. The San Miguel Foundation works with our
						partners to create solutions on the ground and at a people level.
					</p>
					<p>[_Button_]</p>
				</ParallaxGrid>

				<ColumnSection direction={'reverse'}>
					<>
						<h2 className='heading-4 split-color'>
							Environmental <b>and Other Programs</b>
						</h2>
						<p>
							The environmental program of San Miguel Foundation Inc. covers the
							protection of land, water, and air. On a smaller scale, the
							Foundation conducts tree-planting projects on areas identified by
							different San Miguel Corporation (SMC) plants. Tree-planting
							projects are usually scheduled to coincide with plant
							celebrations.
						</p>

						<p>
							The Foundation advocates the protection of coastal waters through
							its Coastal Resource Management, which engages in mangrove
							reforestation, artificial reef installation and regeneration of
							marine resources. Training on waste management and donation of
							trash bins through plant facilities are also conducted.
						</p>
					</>
					<>
						<img src='/images/Homepage-1/1.png'></img>
					</>
				</ColumnSection>
			</Curve>
		</>
	);
}

function Column({ images, y }) {
	return (
		<div className='column'>
			{images.map((src, i) => {
				return (
					<motion.div key={i} className='img-container' style={{ y }}>
						<img src={src} alt='image' fill />
					</motion.div>
				);
			})}
		</div>
	);
}
