import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import PageBanner from '@/cms-components/PageBanner/PageBanner';

import Section from '@/cms-components/Section/Section';
export default function Top20Stockholders() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Exchange Where Listed'} noBg='true' />

				<Section columnCount={3}>
					<div className='column text-content'></div>
				</Section>
			</Fade>
		</>
	);
}
