import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import { motion, useScroll } from 'framer-motion';
import { useRef } from 'react';

import Button from '@/components/button/button';

import Link from 'next/link';

import { AspectRatio, Badge, Flex } from '@chakra-ui/layout';

import { basePath } from '@/hooks/use-basepath';

import Section from '@/cms-components/Section/Section';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import { NewsItem } from '../../corporate/news';

export default function Kaunlaran() {
	const kol = useRef(null);
	const { scrollYprogress } = useScroll({
		target: kol,
		offset: ['start end', 'end start'],
	});

	const kaunlaran_items = [
		{
			link: '/',
			img: basePath + '/images/News/n1.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			desc: 'Non dapibus eget dictum congue neque nibh. Feugiat sapien cras felis tristique morbi sit sit vel. Dolor neque morbi tortor sit tincidunt semper.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n2.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n3.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n4.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n5.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
	];
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Kaunlaran Online'} noBg={true} />
				<Section columnCount={2}>
					<div className='column'>
						<p>
							<b>Kaunlaran Online</b> Non dapibus eget dictum congue neque nibh.
							Feugiat sapien cras felis tristique morbi sit sit vel. Dolor neque
							morbi tortor sit tincidunt semper. Non dapibus eget dictum congue
							neque nibh. Feugiat sapien cras felis tristique morbi sit sit vel.
							Dolor neque morbi tortor sit tincidunt semper.
						</p>
						<div
							className='kaunlaran-grid'
							style={{
								display: 'grid',
								gridTemplateColumns: '1fr 1fr',
								gap: '2rem',
							}}>
							<img src={`${basePath}/images/Kaunlaran-2.png`} />
							<img src={`${basePath}/images/Kaunlaran-3.png`} />
						</div>
					</div>
					<div className='column'>
						<div className='image-content'>
							<div className='img-container'>
								<img src={`${basePath}/images/Kaunlaran-1.png`} />
							</div>
						</div>
					</div>
				</Section>
				<Section columnCount={4}>
					<div className='column' style={{ flex: '1 1 60rem' }}>
						<div className='column'>
							<h2 className='heading-2'>Featured Articles</h2>
							<p className='subheading'>
								Non dapibus eget dictum congue neque nibh. Feugiat sapien cras
								felis tristique morbi sit sit vel. Dolor neque morbi tortor sit
								tincidunt semper.
							</p>
						</div>
						<div className='kaunlaran-featured column'>
							<div className='img-container'>
								<img src={`${kaunlaran_items[0].img}`} />
							</div>
							<div className='desc-container'>
								<div className='news-date small-text'>
									{kaunlaran_items[0].date}
								</div>
								<h2 className='heading-3 news-title'>
									{kaunlaran_items[0].title}
								</h2>
								<p>{kaunlaran_items[0].desc}</p>
								<p>
									<Button link='/news/inner' className={'btn-bordered pri'}>
										Read More
									</Button>
								</p>
							</div>
						</div>
					</div>
					{kaunlaran_items.map((news, index) => {
						return (
							<div className='column' key={`NewsItem_` + index}>
								<NewsItem
									link={news.link}
									index={index}
									title={news.title}
									date={news.date}
									img={news.img}
									direction={'horizontal'}
								/>
							</div>
						);
					})}
				</Section>
			</Fade>
		</>
	);
}
