import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

export default function EnvironmenalProgram() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Curve>
				<PageBanner
					title={'Environment and Other Programs'}
					direction='center'
				/>

				<Section containerSize='small'>
					<div className='column'>
						<h2 className='heading-3'>Water for All</h2>
						<p>
							In 2017, even as our water management efficiency levels were
							already among the highest in the country, we chose to make our
							most significant commitment yet to water sustainability. We
							launched “Water for All,” our Group-wide program to cut
							non-product, utility water use by 50% by 2025.
						</p>
						<p>
							We established the SMC Water Council, comprised of technical
							representatives from each of our operating businesses. They
							establish and monitor water-saving measures and set water
							consumption goals across our plants and offices nationwide. We
							have since been implementing several programs across the Group to
							achieve our target. This includes eliminating the wastage of water
							by adopting stricter measures to improve water use efficiency;
							utilizing water-saving technologies; and implementing conservation
							programs. All facilities and machinery are closely monitored for
							any signs of leakage and malfunction that could lead to wastage.
							Fixing leaks has also contributed significantly to our water
							reduction efforts. We have increased the recycling and reuse of
							water across all our operations and have maximized our utilization
							of desalinated seawater.
						</p>
						<p>
							We have also built new rainwater collection features and
							retrofitted or upgraded older facilities to enable rainwater
							harvesting. Our businesses optimize their wastewater treatment
							facilities and constantly try to make greater use of treated
							greywater for non-essential purposes. More significantly, we
							continue to reduce groundwater use, even as we work with
							communities to protect these water sources.
						</p>
						<h2 className='heading-3'>River cleanup initiative</h2>
						<p>
							In August 2022, San Miguel Corporation completed the Tullahan
							River cleanup initiative, after 27 months of operations. SMC was
							able to extract over 1.2 million MT of silt and solid waste from
							an 11-kilometer stretch of the river system, spanning four major
							cities. In partnership with the DENR, the project represented the
							largest river cleanup undertaken by any private company. This
							accomplishment would only be outpaced in scale and scope a year
							later by our next initiative— the Pasig River cleanup. By February
							2023, just 20 months into the project, we reached the one million
							MT milestone of silt and solid waste removed from the Pasig River,
							long a symbol of pollution and neglect in the Philippines. We have
							also begun the clean-up of Bulacan’s Meycauayan river, to help
							alleviate perennial flooding. Our river initiatives demonstrate
							SMC’s willingness to go beyond what is expected. While some of our
							projects are located along these rivers, our efforts to improve
							the health of our waterways are driven by our desire to positively
							impact the environment and the communities we serve. In
							particular, the wide-scale impacts of flooding and pollution on
							our cities and people have compelled us to take decisive action.
						</p>
						<p>
							In a 2021 study published in OurWorldinData. org, the Pasig River
							emerged as the top plasticsemitting river responsible for the
							world’s ocean plastics. Meanwhile, the Tullahan and Meycauayan
							Rivers are ranked four and five on that list. Four other
							Philippine rivers—the Pampanga, Libmanan, Rio Grande de Mindanao,
							and Agno rivers—also made it in the top 10 of that same global
							list. Keeping our rivers clean will help reduce the amount of
							plastic waste that pollutes our oceans, improve water quality,
							support biodiversity, and mitigate threats to traditional fishing
							grounds. But just as important is deepening and widening them to
							mitigate decades of siltation and pollution that have rendered
							them unable to serve their purpose of directing flood waters away
							from our cities. Fully rehabilitating our rivers will of course
							take more than just ridding them of silt and garbage. To transform
							our rivers into thriving ecosystems, it will require the
							collective efforts of various stakeholders, including government,
							communities, and private sector partners. While it seems like a
							daunting endeavor, taking the first steps toward restoration is a
							crucial part and one that SMC is more than willing to take.
						</p>
						<h2 className='heading-3'>Waste-to-resource</h2>
						<p>
							We make conscious and disciplined efforts to recycle coal
							combustion residuals (CCR), mainly as an aggregate material for
							cement manufacturing. We utilize coal ash as a supplementary
							material and as a substitute for clinker, an input used to
							strengthen cement. While coal ash cannot completely replace
							clinker in cement production, using it as an add-on contributes to
							reducing GHG emissions. SMGP’s Limay Power Plant and Malita Power
							Plant have been successful in recycling as much as 80-90% and
							70-80% of their coal ash, respectively. This is achieved through
							recycling coal ash from Limay Power Plant at Petron Bataan
							Refinery’s cogeneration facility, reducing the plants’ consumption
							of virgin inert materials (e.g. silica sand), and supplying NCC
							and Southern Concrete with aggregate material for cement
							production. Since not all CCR can be recycled, we put significant
							efforts and investments in proper storage of the excess. We
							strictly follow and comply with the DENR’s Water Quality
							Guidelines and General Effluent Standard of 2016 (DAO 201608) to
							ensure proper management, storage, and monitoring.
						</p>
						<p>
							We also value the involvement of our partner communities. We carry
							out information, education, and communication campaigns to discuss
							specific measures undertaken to ensure that our activities do not
							cause harm to the environment and to the health of individuals. We
							also employ biomats made up of biodegradable natural fibers, such
							as straw, coir, and jute, to cover the ash and prevent erosion and
							blowing away. The biomats have seedlings already planted, which
							provide immediate soil stabilization and protection, and
							strengthen vegetation on slopes. This area will eventually be
							covered in trees by the end of its 25-year lifespan.
						</p>
						<p>
							TO KNOW MORE,{' '}
							<a href='/sustainability'>
								DOWNLOAD OUR LATEST SUSTAINABILITY REPORT
							</a>
						</p>
					</div>
				</Section>
			</Curve>
		</>
	);
}
