import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion } from 'framer-motion';

import { getColors } from '@/hooks/use-color';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import ImageSlider from '@/cms-components/ImageSlider/ImageSlider';
import { useState } from 'react';

export default function OurCompany() {
	const [selected, setSelected] = useState(0);

	const fnb = [
		{
			img: `${basePath}/images/OurCompany/fnb-1.png`,
		},
		{
			img: `${basePath}/images/OurCompany/fnb-2.png`,
		},
	];
	const packaging = [
		{
			img: `${basePath}/images/OurCompany/packaging-1.png`,
		},
		{
			img: `${basePath}/images/OurCompany/packaging-2.png`,
		},
		{
			img: `${basePath}/images/OurCompany/packaging-3.png`,
		},
	];
	const fo = [
		{
			img: `${basePath}/images/OurCompany/fo-1.png`,
		},
		{
			img: `${basePath}/images/OurCompany/fo-2.png`,
		},
		{
			img: `${basePath}/images/OurCompany/fo-3.png`,
		},
	];
	const power = [
		{
			img: `${basePath}/images/OurCompany/power-1.png`,
		},
		{
			img: `${basePath}/images/OurCompany/power-2.png`,
		},
		{
			img: `${basePath}/images/OurCompany/power-3.png`,
		},
	];
	const infra = [
		{
			img: `${basePath}/images/OurCompany/infra-1.png`,
		},
		{
			img: `${basePath}/images/OurCompany/infra-2.png`,
		},
		{
			img: `${basePath}/images/OurCompany/infra-3.png`,
		},
	];
	const cem = [
		{
			img: `${basePath}/images/OurCompany/Cem-1.png`,
		},
	];

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Curve>
				<PageBanner title={'Corporate Structure'} direction='center' />

				<Section
					sectionStyle={{
						paddingTop: '3rem',
						paddingBottom: '4rem',
					}}>
					<div className='column'>
						<div className='img-content'>
							<div className='img-container'>
								<img src={`${basePath}/images/CorporateStructure.png`} />
							</div>
						</div>
					</div>
				</Section>
			</Curve>
		</>
	);
}
