import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import PageBanner from '@/cms-components/PageBanner/PageBanner';

import Section from '@/cms-components/Section/Section';
export default function Top20Stockholders() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title={'Top 20 Stockholders'} noBg='true' />

				<Section columnCount={3}>
					<div className='column text-content'>
						<p>
							As of December 31, 2022 <br />
							<span className='small-text'>*updated Annually</span>
						</p>

						<small>
							<table className='table table-responsive top20'>
								<tbody>
									<tr className='upper table__header'>
										<th>Rank</th>
										<th>Stockholder Name</th>
										<th>Common</th>
										<th>Preferred 2-F</th>
										<th>Preferred 2-I</th>
										<th>Preferred 2-J</th>
										<th>Preferred 2-K</th>
										<th>Total Shares</th>
										<th>% Of O/S</th>
									</tr>
									<tr>
										<td>1</td>
										<td>Top Frontier Investment Holdings, Inc.</td>
										<td data-label='Common: '>1,424,111,611</td>
										<td data-label='Preferred 2-F: '>0</td>
										<td data-label='Preferred 2-I: '>0</td>
										<td data-label='Preferred 2-J: '>0</td>
										<td data-label='Preferred 2-K: '>0</td>
										<td data-label='Total Shares: '>1,424,111,611</td>
										<td data-label='% Of O/S: '>44.129286%</td>
									</tr>
									<tr>
										<td>2</td>
										<td>PCD Nominee Corporation (Filipino)</td>
										<td data-label='Common: '>290,538,037</td>
										<td data-label='Preferred 2-F: '>194,469,800</td>
										<td data-label='Preferred 2-I: '>149,531,030</td>
										<td data-label='Preferred 2-J: '>129,378,237</td>
										<td data-label='Preferred 2-K: '>180,654,860</td>
										<td data-label='Total Shares: '>944,571,964</td>
										<td data-label='% Of O/S: '>29.269676%</td>
									</tr>
									<tr>
										<td>3</td>
										<td>Privado Holdings, Corp.</td>
										<td data-label='Common: '>368,140,516</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>368,140,516</td>
										<td data-label='% Of O/S: '>11.407658%</td>
									</tr>
									<tr>
										<td>4</td>
										<td>PCD Nominee Corporation (Non-filipino)</td>
										<td data-label='Common: '>116,142,883</td>
										<td data-label='Preferred 2-F: '>1,717,390</td>
										<td data-label='Preferred 2-I: '>1,820,950</td>
										<td data-label='Preferred 2-J: '>754,760</td>
										<td data-label='Preferred 2-K: '>2,314,340</td>
										<td data-label='Total Shares: '>122,750,323</td>
										<td data-label='% Of O/S: '>3.803693%</td>
									</tr>
									<tr>
										<td>5</td>
										<td>Republic of the Philippines</td>
										<td data-label='Common: '>27,636,339</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>27,636,339</td>
										<td data-label='% Of O/S: '>0.856374%</td>
									</tr>
									<tr>
										<td>6</td>
										<td>SGOC Holdings Corporation</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>2,700,000</td>
										<td data-label='Preferred 2-J: '>16,098,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>18,798,000</td>
										<td data-label='% Of O/S: '>0.582498%</td>
									</tr>
									<tr>
										<td>7</td>
										<td>CJJ Holdings Corporation</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>16,098,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>16,098,000</td>
										<td data-label='% Of O/S: '>0.498833%</td>
									</tr>
									<tr>
										<td>8</td>
										<td>LOCC Holdings Corporation</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>16,098,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>16,098,000</td>
										<td data-label='% Of O/S: '>0.498833%</td>
									</tr>
									<tr>
										<td>9</td>
										<td>Tincobar Holdings Corporation</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>16,098,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>16,098,000</td>
										<td data-label='% Of O/S: '>0.498833%</td>
									</tr>
									<tr>
										<td>10</td>
										<td>Saint Bruno Holdings Corporation</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>16,098,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>16,098,000</td>
										<td data-label='% Of O/S: '>0.498833%</td>
									</tr>
									<tr>
										<td>11</td>
										<td>San Miguel Brewery Inc. Retirement Plan</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>8,000,000</td>
										<td data-label='Preferred 2-I: '>6,153,600</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>14,153,600</td>
										<td data-label='% Of O/S: '>0.438581%</td>
									</tr>
									<tr>
										<td>12</td>
										<td>Juan Bruno Holdings OPC</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>450,000</td>
										<td data-label='Preferred 2-J: '>13,415,000</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>13,865,000</td>
										<td data-label='% Of O/S: '>0.429638%</td>
									</tr>
									<tr>
										<td>13</td>
										<td>Petron Corporation Employees&apos; Retirement Plan</td>
										<td data-label='Common: '>12,237,100</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>12,237,100</td>
										<td data-label='% Of O/S: '>0.379194%</td>
									</tr>
									<tr>
										<td>14</td>
										<td>Greater Reunion Holdiongs Inc.</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>382,500</td>
										<td data-label='Preferred 2-J: '>11,402,750</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>11,785,250</td>
										<td data-label='% Of O/S: '>0.365192%</td>
									</tr>
									<tr>
										<td>15</td>
										<td>Millenium Energy, Inc.</td>
										<td data-label='Common: '>10,807,380</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>10,807,380</td>
										<td data-label='% Of O/S: '>0.334891%</td>
									</tr>
									<tr>
										<td>16</td>
										<td>San Miguel Corp. Retirement Plan Fip</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>5,333,400</td>
										<td data-label='Preferred 2-I: '>2,900,000</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>8,233,400</td>
										<td data-label='% Of O/S: '>0.255130%</td>
									</tr>
									<tr>
										<td>17</td>
										<td>Social Security System</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>7,328,500</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>7,328,500</td>
										<td data-label='% Of O/S: '>0.227090%</td>
									</tr>
									<tr>
										<td>18</td>
										<td>Sysmart Corporation</td>
										<td data-label='Common: '>5,100,607</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>-</td>
										<td data-label='Preferred 2-J: '>-</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>5,100,607</td>
										<td data-label='% Of O/S: '>0.158054%</td>
									</tr>
									<tr>
										<td>19</td>
										<td>Kay Mitoy Holdings Incorporated</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>112,500</td>
										<td data-label='Preferred 2-J: '>3,353,750</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>3,466,250</td>
										<td data-label='% Of O/S: '>0.107410%</td>
									</tr>
									<tr>
										<td>20</td>
										<td>Makhia Holdings Inc.</td>
										<td data-label='Common: '>0</td>
										<td data-label='Preferred 2-F: '>-</td>
										<td data-label='Preferred 2-I: '>112,500</td>
										<td data-label='Preferred 2-J: '>3,353,750</td>
										<td data-label='Preferred 2-K: '>-</td>
										<td data-label='Total Shares: '>3,466,250</td>
										<td data-label='% Of O/S: '>0.107410%</td>
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td>&nbsp;</td>
										<td data-label='Common: '>2,254,714,473</td>
										<td data-label='Preferred 2-F: '>216,849,090</td>
										<td data-label='Preferred 2-I: '>164,163,080</td>
										<td data-label='Preferred 2-J: '>242,148,247</td>
										<td data-label='Preferred 2-K: '>182,969,200</td>
										<td data-label='Total Shares: '>3,060,844,140</td>
										<td data-label='% Of O/S: '>94.85%</td>
									</tr>
								</tbody>
							</table>
						</small>
						<div className='top-total'>
							<p>
								<b>TOTAL NO. OF SHARES :</b> <span>3,227,135,055</span>
							</p>
							<p>
								<b>TOTAL NO. OF DISTINCT STOCKHOLDERS:</b> <span>33,873</span>
							</p>
							<p>
								<b>TOTAL NO. OF ACCOUNTS :</b> <span>33,889</span>
							</p>
						</div>
					</div>
				</Section>
			</Curve>
		</>
	);
}
