import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';

import { useDimensions } from '@/hooks/use-dimension';

import SingleParallax from '@/cms-components/SingleParallax/single-parallax';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

import { CgPlayButtonO } from 'react-icons/cg';
import VideoContent from '@/cms-components/VideoContent/Video';
import Column from '@/cms-components/Column/column';

export default function OurHistory() {
	const parent1 = useRef(null);

	const { width: w1 } = useDimensions(parent1);

	const { scrollYProgress: scrollYProgress_start1 } = useScroll({
		target: parent1,
		offset: ['start end', 'end start'],
	});

	// const springValue1 = useSpring(scrollYProgress_start1, {
	// 	stiffness: 100,
	// 	damping: 30,
	// 	restDelta: 0.001,
	// });

	const xVal = useTransform(scrollYProgress_start1, [0, 1], ['0vw', `-100vw`]);

	const xVal2 = useTransform(scrollYProgress_start1, [0, 1], ['-100vw', `0vw`]);

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<meta
					http-equiv='Content-Security-Policy'
					content='frame-src youtube.com www.youtube.com'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Our History'} direction='center' />

				<Section direction={'center'}>
					<Column>
						<h2 className='heading-2'>Proud Beginnings</h2>
					</Column>
					<Column>
						<iframe
							width='914'
							height='514'
							src='https://www.youtube.com/embed/sEakdgzsAvE'
							title='128 years of San Miguel Corporation'
							frameborder='0'
							allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
							referrerpolicy='strict-origin-when-cross-origin'
							allowfullscreen
							style={{ maxWidth: '100%', width: '100%' }}></iframe>
						{/* <VideoContent /> */}
					</Column>
				</Section>
				<Section
					direction={'center'}
					containerSize='small'
					sectionStyle={{ minHeight: '0', paddingTop: 0 }}>
					<Column>
						<p>
							Established in 1890, La Fabrica de Cerveza de San Miguel,
							Southeast Asia’s first brewery produced and bottled what would
							eventually become one of the bestselling beers in the region.
							Within the span of a generation, San Miguel Beer would become an
							icon among beer drinkers.
						</p>
					</Column>
				</Section>
				<motion.div
					style={{ paddingTop: 0 }}
					className='section-content img-section full no-min-height'
					ref={parent1}>
					<div className='container-fluid-width' style={{ rowGap: 0 }}>
						<Column>
							<div className='marquee'>
								<motion.div
									className='marquee-overflow'
									initial={{
										x: 0,
									}}
									// style={{ x: xVal }}
									animate={{
										x: '-100vw',
									}}
									transition={{
										repeat: Infinity,
										duration: 25,
										ease: 'linear',
									}}>
									<div
										className='grid'
										style={{
											gridTemplateColumns:
												'1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr',
										}}>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/11.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/12.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/13.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/14.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/15.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/11.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/12.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/13.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/14.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/15.jpg`} />
											</SingleParallax>
										</div>
									</div>
								</motion.div>
							</div>
							<div className='marquee'>
								<motion.div
									className='marquee-overflow'
									initial={{
										x: '-100vw',
									}}
									animate={{
										x: '0vw',
									}}
									transition={{
										repeat: Infinity,
										duration: 25,
										ease: 'linear',
									}}>
									<div
										className='grid'
										style={{
											gridTemplateColumns:
												'1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr',
										}}>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/1.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/2.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/3.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/4.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/5.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/1.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/2.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/3.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/4.jpg`} />
											</SingleParallax>
										</div>
										<div>
											<SingleParallax
												scrollYProgress_start={scrollYProgress_start1}>
												<img src={`${basePath}/images/OurHistory/5.jpg`} />
											</SingleParallax>
										</div>
									</div>
								</motion.div>
							</div>
						</Column>
					</div>
				</motion.div>
			</Fade>
		</>
	);
}
