import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import VideoContent from '@/cms-components/VideoContent/Video';
import Section from '@/cms-components/Section/Section';
import Column from '@/cms-components/Column/column';
export default function BoardCommittees() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Board Committees'} direction='center' />

				<Section
					columnCount={3}
					containerStyle={{ lineHeight: 1.5, gap: '3rem' }}>
					<Column>
						<p class='heading-5'>
							<b>EXECUTIVE COMMITTEE</b>
						</p>
						<p>
							Chairman
							<br />
							<b>
								<i>Vacant</i>
							</b>
						</p>
						<p>
							Vice Chairman
							<br />
							<b>Ramon S. Ang</b>
						</p>
						<p>
							Members
							<br />
							<b>Menardo R. Jimenez</b>
							<br />
							<b>Estelito P. Mendoza</b>
							<br />
							<b>Iñigo Zobel</b>
							<br />
						</p>
					</Column>
					<Column>
						<header class='heading-5'>
							<b>AUDIT AND RISK OVERSIGHT COMMITTEE</b>
						</header>
						<p>
							Chairman
							<br />
							<b>Margarito B. Teves</b>
						</p>
						<p>
							Members
							<br />
							<b>Teresita J. Leonardo - De Castro</b>
							<br />
							<b>Estelito P. Mendoza</b>
							<br />
							<b>Reynato S. Puno</b>
							<br />
							<b>Diosdado M. Peralta</b>
							<br />
						</p>
						<p class='doc-links'>
							<a
								target='_blank'
								href='/storage/files/reports/SMC-Audit-and-Risk-Oversight-Committee-Charter-10-Aug-2017.pdf'
								style={{
									fontStyle: 'italic',
									fontWeight: 700,
								}}>
								Audit and Risk Oversight Committee Charter
							</a>
							<br />
							<a
								target='_blank'
								href='/storage/files/reports/SEC_Form-17_SMC-Charter-of-Internal-Audit-03.16__.17_1_.pdf'
								style={{
									fontStyle: 'italic',
									fontWeight: 700,
								}}>
								Internal Audit Charter
							</a>
						</p>
					</Column>
					<Column>
						<header class='heading-5'>
							<b>RELATED PARTY TRANSACTIONS COMMITTE</b>
						</header>
						<p>
							Chairman
							<br />
							<b>Teresita J. Leonardo – De Castro</b>
						</p>
						<p>
							Members
							<br />
							<b>Joselito D. Campos, Jr.</b>
							<br />
							<b>Alexander J. Poblador</b>
							<br />
							<b>Reynato S. Puno</b>
							<br />
							<b>Margarito B. Teves</b>
						</p>
						<p class='doc-links'>
							<a
								target='_blank'
								href='/storage/files/reports/SMC-Related-Party-Transactions-Committee-Charter-10-Aug-2017.pdf'
								style={{
									fontStyle: 'italic',
									fontWeight: 700,
								}}>
								Related Party Transactions Committee Charter
							</a>
						</p>
					</Column>
					<Column>
						<header class='heading-5'>
							<b>CORPORATE GOVERNANCE COMMITTEE</b>
						</header>
						<p>
							Chairman
							<br />
							<b>Reynato S. Puno</b>
						</p>
						<p>
							Members
							<br />
							<b>Aurora T. Calderon</b>
							<br />
							<b>Diosdado M. Peralta</b>
							<br />
							<b>Menardo R. Jimenez</b>
							<br />
							<b>Margarito B. Teves</b>
						</p>
						<p class='doc-links'>
							<a
								target='_blank'
								href='/storage/files/reports/SMC-Corporate-Governance-Committee-Charter-10-Aug-2017.pdf'
								style={{
									fontStyle: 'italic',
									fontWeight: 700,
								}}>
								Corporate Governance Committee Charter
							</a>
						</p>
					</Column>

					<Column>
						<header class='heading-5'>
							<b>BOARD SUSTAINABILITY COMMITTEE</b>
						</header>
						<p>
							Chairman
							<br />
							<b>Teresita J. Leonardo-de Castro</b>
						</p>
						<p>
							Members
							<br />
							<b>Aurora T. Calderon</b>
							<br />
							<b>Diosdado M. Peralta</b>
							<br />
							<b>Ernesto M. Pernia</b>
							<br />
							<b>Alexander J. Poblador</b>
						</p>
						<p class='doc-links'>
							<a
								target='_blank'
								href='/storage/files/reports/SMC_Sustainability_Committee_Charter_-_3_August_2023_[for_uploading).pdf'
								style={{
									fontStyle: 'italic',
									fontWeight: 700,
								}}>
								Board Sustainability Committee Charter
							</a>
						</p>
					</Column>
				</Section>
			</Fade>
		</>
	);
}
