import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';

import Button from '@/components/button/button';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import useAnim from '@/hooks/use-anim';

import Link from 'next/link';

import gsap from 'gsap';
import { pageTranslate } from '@/hooks/pageAnim';
import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';
import FloatingImages from '@/cms-components/FloatingImages/floatingimages';

import { basePath } from '@/hooks/use-basepath';
import SingleParallax from '@/components/single-parallax/single-parallax';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import { NewsItem } from '@/pages/news';

export default function WalangIwanan() {
	const parent1 = useRef(null);
	const { scrollYProgress: scrollYProgress_start1 } = useScroll({
		target: parent1,
		offset: ['start end', 'end start'],
	});

	const news_section = useRef(null);

	const [modal, setModal] = useState({
		active: false,
		index: 0,
		link: '',
	});

	const newsItems = [
		{
			title:
				'SMC bests other PH firms; jumps to 43rd in Forbes’ World’s Best Employers list—after ranking high in Time’s World’s Best Companies',
			desc: 'Since 2013, in the aftermath of typhoons Sendong and Yolanda, San Miguel Corporation (SMC) has been at the forefront of building resilient housing communities nationwide.',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n1.png',
			link: '/news/inner',
		},
		{
			title:
				'SMC, Ayala ink agreement to integrate Arca South to Skyway Stage 4 project',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n2.png',
			link: '/news/inner',
		},
		{
			title: "SMC's nine-month profit more than doubles to ₱31.2 billion",
			date: 'November 28, 2023',
			img: '',
			link: '/news/inner',
		},
		{
			title:
				'SMB delivers solid nine-month results amidst higher volumes, improved market conditions',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n4.png',
			link: '/news/inner',
		},
	];

	useEffect(() => {
		console.log(modal.index);
	}, [modal.index]);

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner
					title={'Walang Iwanan Our Covid-19 Response'}
					direction='center'
				/>

				<p>[_VIDEO_]</p>
				<Section columnCount={2}>
					<div className='column'>
						<div className='text-content'>
							<h3 className='heading-4'>
								Our efforts in the wake of the global pandemic are guided by our
								malasakit.
							</h3>
							<p>
								In the fight against Covid-19, we have mounted the largest
								private sector response to the crisis. As of October 2020, we
								have mobilized over P13 billion to help the country—specially
								frontliners and the poorest communities.
							</p>
							<p>
								Our contributions include hundreds of millions in food and
								medical equipment, free fuel and waived toll fees for
								frontliners, and the construction of quarantine facilities. We
								also repurposed our liquor plants to manufacture disinfecting
								alcohol for hospitals and clinics.
							</p>
							<p>
								In 2021, our efforts continue to help the country recover from
								the COVID-19 global pandemic.
							</p>
						</div>
					</div>
					<div className='column'>
						<div className='image-content'>
							<div className='img-container'>
								<img src={`${basePath}/images/OurCompany/Our-Company.png`} />
							</div>
						</div>
					</div>
				</Section>

				<FullPageBanner>
					<img src={`${basePath}/images/WalangIwanan/b1.png`} />
				</FullPageBanner>

				<FloatingImages
					images={[
						basePath + '/images/WalangIwanan/1.png',
						basePath + '/images/WalangIwanan/2.png',
						basePath + '/images/WalangIwanan/3.png',
					]}>
					<div className='desc-container'>
						<p>
							Our efforts in the wake of the global pandemic are guided by our
							malasakit.
						</p>
						<p>
							In the fight against Covid-19, we have mounted the largest private
							sector response to the crisis. As of October 2020, we have
							mobilized over P13 billion to help the country—specially
							frontliners and the poorest communities.
						</p>
						<p>
							Our contributions include hundreds of millions in food and medical
							equipment, free fuel and waived toll fees for frontliners, and the
							construction of quarantine facilities. We also repurposed our
							liquor plants to manufacture disinfecting alcohol for hospitals
							and clinics.
						</p>
						<p>
							In 2021, our efforts continue to help the country recover from the
							COVID-19 global pandemic.
						</p>
					</div>
				</FloatingImages>

				<FullPageBanner>
					<img src={`${basePath}/images/WalangIwanan/b2.png`} />
				</FullPageBanner>

				<Section>
					<div className='column'>
						<div
							className='news-featured'
							ref={parent1}
							style={{ backgroundImage: `url(${newsItems[0].img})` }}>
							<div className='desc-container'>
								<div className='news-date small'>{newsItems[0].date}</div>
								<h2 className='heading-5 news-title'>{newsItems[0].title}</h2>
								{/* <p>{newsItems[0].desc}</p> */}
								<p>
									<Button link='/news/inner' className={'btn-bordered pri'}>
										Read More
									</Button>
								</p>
							</div>
						</div>
					</div>
				</Section>
				<Section columnCount={2}>
					{newsItems.map((news, index) => {
						return (
							<div className='column' key={`NewsItem_` + index}>
								<NewsItem
									link={news.link}
									index={index}
									title={news.title}
									date={news.date}
									img={news.img}
								/>
							</div>
						);
					})}
				</Section>
				<motion.div
					className='section-content news-section'
					{...useAnim(pageTranslate(1))}>
					<div className='container-fluid-width medium'>
						<div className='news-featured' ref={parent1}>
							<div className='desc-container'>
								<div className='news-date size-limit'>{newsItems[0].date}</div>
								<h2 className='heading-3 news-title'>{newsItems[0].title}</h2>
								<p>{newsItems[0].desc}</p>
								<Button
									link='/our-business/inner'
									className={'btn-bordered pri'}>
									Read More
								</Button>
							</div>
							<div className='img-container'>
								<SingleParallax scrollYProgress_start={scrollYProgress_start1}>
									<img src={newsItems[0].img} />
								</SingleParallax>
							</div>
						</div>
						<div className='news-list'></div>
					</div>
				</motion.div>
			</Curve>
		</>
	);
}
