import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import SampleVideo from '@/components/SampleVideo/sample-video';
import OurBusinesses from '@/cms-components/OurBusinesses/OurBusinesses';

import { motion } from 'framer-motion';
import { useContext } from 'react';

import Button from '@/components/button/button';
import PageCTA from '@/cms-components/PageCTA/PageCTA';

import { basePath } from '@/hooks/use-basepath';
import MainBanner from '@/cms-components/MainBanner/MainBanner';
import Pillar from '@/cms-components/Pillar/Pillar';
import OurProject from '@/cms-components/OurProject/OurProject';

import { TokenContext } from './_app.js';

export default function Home() {
	const token = useContext(TokenContext);
	// const ur
	const pillar_content1 = {
		focus: `${basePath}/images/Homepage-1/test/test-1-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-1-1.png`,
		text1: 'The San Miguel Group Vision',
		text2: 'A resilient and globally competitive Philippines',
		text3: 'where everyone can enrich and enjoy their lives.',
	};

	const pillar_content2 = {
		focus: `${basePath}/images/Homepage-1/test/test-2-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-2-1.png`,
		text1: 'Our Core Purpose',
		text2:
			'To lead in nation-building by creating opportunities that will uplift generation of Filipinos,',
		text3:
			'allowing all to share in the rewards of sustainable development and prosperity.',
	};

	const pillar_content3 = {
		focus: `${basePath}/images/Homepage-1/test/test-3-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-3-1.png`,
		text1: 'Our Core Value',
		text2: 'Malasakit is at the core of who we are as a company.',
		text3: 'EXELLENCE <br/>ACCOUNTABILITY <br/>SUSTAINABILITY.',
	};

	const images = [
		{
			url: `${basePath}/images/Homepage-1/NewBanner/A.jpg`,
			start: '5:00',
			end: '7:59',
		},
		{
			url: `${basePath}/images/Homepage-1/NewBanner/B.jpg`,
			start: '8:00',
			end: '15:59',
		},
		{
			url: `${basePath}/images/Homepage-1/NewBanner/C.jpg`,
			start: '16:00',
			end: '18:59',
		},
		{
			url: `${basePath}/images/Homepage-1/NewBanner/D.jpg`,
			start: '19:00',
			end: '5:00',
		},
	];

	const today = new Date();
	let url;
	images.map((image, index) => {
		let imageTimeStart = new Date(
			today.getFullYear(),
			today.getMonth(),
			today.getDate(),
			image.start.split(':')[0],
			image.start.split(':')[1]
		);
		let imageTimeEnd = new Date(
			today.getFullYear(),
			today.getMonth(),
			today.getDate(),
			image.end.split(':')[0],
			image.end.split(':')[1]
		);

		if (today >= imageTimeStart && today <= imageTimeEnd) {
			url = image.url;
		}
		if (index === 3) {
			console.log(imageTimeStart);
			console.log(today);
			console.log(imageTimeEnd);

			if (imageTimeEnd >= today || today >= imageTimeStart) {
				url = image.url;
			}
		}
	});

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href={`${basePath}/favicon.ico`} />
			</Head>
			<Curve>
				<motion.section className='main-banner'>
					<motion.div className='banner-parallax'>
						<motion.div
							animate={{
								backgroundImage: `url(${url})`,
							}}></motion.div>
						<motion.h1
							className='heading-1'
							style={{
								x: '-50%',
								opacity: 1,
							}}>
							Your World Made Better
						</motion.h1>
					</motion.div>
				</motion.section>
				<SampleVideo />
				<Pillar content={pillar_content1} position={'right'}>
					<div>
						<p></p>
					</div>
				</Pillar>
				<Pillar content={pillar_content2} position={'left'} simple={true} />
				<Pillar content={pillar_content3} position={'right'} />
				<OurBusinesses />
				<OurProject />
				<motion.div
					className='section-content text-center'
					style={{
						color: 'white',
						minHeight: '100vh',
						alignItems: 'flex-start',
						backgroundImage: `url("${basePath}/images/Homepage-1/Malasakit-bg.png"), linear-gradient(#3883ac, #aabf6b, #b58282)`,
						backgroundSize: 'cover',
					}}>
					<div
						className='container-fluid-width'
						style={{
							justifyContent: 'center',
						}}>
						<div className='column'>
							<h2 className='heading-2'>
								<i>Malasakit</i>
							</h2>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor incididunt ut labore et dolore magna aliqua.
							</p>
							<p>
								<Button
									link='/our-business/inner'
									className='btn-bordered white'>
									Read More
								</Button>
							</p>
							<img
								src={`${basePath}/images/Homepage-1/Malasakit.png`}
								style={{
									display: 'block',
									width: '100%',
									marginTop: '5rem',
									marginBottom: '-6rem',
								}}
							/>
						</div>
					</div>
				</motion.div>
				<PageCTA />
			</Curve>
		</>
	);
}
