import Head from 'next/head';
import Curve from '@/components/Layout/Curve';
import Parallax from '@/components/Parallax/parallax';
import SampleVideo from '@/components/SampleVideo/sample-video';
import OurBusinesses from '@/cms-components/OurBusinesses/OurBusinesses';

import { motion, useScroll } from 'framer-motion';
import { useRef } from 'react';
import { getColors } from '@/hooks/use-color';
import Card from '@/components/card/card';
import Button from '@/components/button/button';
import PageCTA from '@/cms-components/PageCTA/PageCTA';
import ColumnSection from '@/cms-components/ColumnSection/ColumnSection';

import { basePath } from '@/hooks/use-basepath';
import MainBanner from '@/cms-components/MainBanner/MainBanner';
import Pillar from '@/cms-components/Pillar/Pillar';
import OurProject from '@/cms-components/OurProject/OurProject';

export default function Home() {
	const pillar_content1 = {
		focus: `${basePath}/images/Homepage-1/test/test-1-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-1-1.png`,
		text1: 'The San Miguel Group Vision',
		text2: 'A resilient and globally competitive Philippines',
		text3: 'where everyone can enrich and enjoy their lives.',
	};

	const pillar_content2 = {
		focus: `${basePath}/images/Homepage-1/test/test-2-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-2-1.png`,
		text1: 'Our Core Purpose',
		text2:
			'To lead in nation-building by creating opportunities that will uplift generation of Filipinoes,',
		text3:
			'allowing all to share in the rewards of sustainable development and prosperity.',
	};

	const pillar_content3 = {
		focus: `${basePath}/images/Homepage-1/test/test-3-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-3-1.png`,
		text1: 'Our Core Value',
		text2: 'Malasakit is at the core of who we are as a company.',
		text3: 'EXELLENCE ACCOUNTABILITY SUSTAINABILITY',
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<MainBanner />
				<SampleVideo />
				<Pillar content={pillar_content1} position={'right'}>
					<div>
						<p></p>
					</div>
				</Pillar>
				<Pillar content={pillar_content2} position={'left'} simple={true} />
				<Pillar content={pillar_content3} position={'right'} />

				<OurBusinesses />
				<OurProject />
				<motion.div
					className='section-content text-center'
					style={{
						color: 'white',
						minHeight: '100vh',
						alignItems: 'flex-start',
						backgroundImage: `url("${basePath}/images/Homepage-1/Malasakit-bg.png"), linear-gradient(#3883ac, #aabf6b, #b58282)`,
						backgroundSize: 'cover',
					}}>
					<div className='container-fluid-width'>
						<h2 className='heading-3'>
							<i>Malasakit</i>
						</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
							eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</p>
						<p>
							<Button link='/our-business/inner' className='btn-bordered white'>
								Read More
							</Button>
						</p>
						<img
							src={`${basePath}/images/Homepage-1/Malasakit.png`}
							style={{
								display: 'block',
								width: '100%',
								marginTop: '5rem',
								marginBottom: '-6rem',
							}}
						/>
					</div>
				</motion.div>

				<PageCTA />
			</Curve>
		</>
	);
}
