import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import SampleVideo from '@/components/SampleVideo/sample-video';
import OurBusinesses from '@/cms-components/OurBusinesses/OurBusinesses';

import { motion } from 'framer-motion';
import { useContext } from 'react';

import Button from '@/components/button/button';
import PageCTA from '@/cms-components/PageCTA/PageCTA';

import { basePath } from '@/hooks/use-basepath';
import MainBanner from '@/cms-components/MainBanner/MainBanner';
import Pillar from '@/cms-components/Pillar/Pillar';
import OurProject from '@/cms-components/OurProject/OurProject';

import { TokenContext } from './_app.js';
import Section from '@/cms-components/Section/Section.js';
import { useGetBannerData } from '@/data/data.js';

export default function Home() {
	const token = useContext(TokenContext);

	const pillar_content1 = {
		focus: `${basePath}/images/Homepage-1/test/test-1-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-1-1.png`,
		text1: 'The San Miguel Group Vision',
		text2: 'A resilient and globally competitive Philippines',
		text3: 'where everyone can enrich and enjoy their lives.',
	};

	const pillar_content2 = {
		focus: `${basePath}/images/Homepage-1/test/test-2-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-2-1.png`,
		text1: 'Our Core Purpose',
		text2:
			'To lead in nation-building by creating opportunities that will uplift generation of Filipinos,',
		text3:
			'allowing all to share in the rewards of sustainable development and prosperity.',
	};

	const pillar_content3 = {
		focus: `${basePath}/images/Homepage-1/test/test-3-2.png`,
		bg: `${basePath}/images/Homepage-1/test/test-3-1.png`,
		text1: 'Our Core Value',
		text2: 'Malasakit is at the core of who we are as a company.',
		text3: 'EXELLENCE <br/>ACCOUNTABILITY <br/>SUSTAINABILITY.',
	};

	const data = [
		{
			img: basePath + '/images/OurBusinesses/food.jpg',
			title: 'Food and Beverage',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/oil.jpg',
			title: 'Oil Refining and Marketing',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/packaging.jpg',
			title: 'Packaging',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/properties.jpg',
			title: 'Properties',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/power.jpg',
			title: 'Power and Energy',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/infrastructure.jpg',
			title: 'Infrastructure',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
		{
			img: basePath + '/images/OurBusinesses/other.jpg',
			title: 'Other Businsesses',
			description:
				'San Miguel Brewery Inc. (SMB) is the largest producer of beer in the Philippines, with nine out of ten beer drinkers preferring its brands.',
			link: '//our-business/inner',
		},
	];

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>

				<link rel='icon' href={`${basePath}/favicon.ico`} />
			</Head>
			<Fade
				customStyle={{
					transformOrigin: 'center 5%',
				}}>
				<MainBanner />
				<SampleVideo />
				<Pillar content={pillar_content1} position={'right'}>
					<div>
						<p></p>
					</div>
				</Pillar>
				<Pillar content={pillar_content2} position={'left'} simple={true} />
				<Pillar content={pillar_content3} position={'right'} />
				<OurBusinesses />
				<OurProject />
				<Section
					sectionClass='text-center'
					containerClass='malasakit-container '
					sectionStyle={{
						textAlign: 'center',
						color: 'white',
						alignItems: 'flex-start',
						backgroundImage: `url("${basePath}/images/Homepage-1/Malasakit-bg.png"), linear-gradient(#3883ac, #aabf6b, #b58282)`,
						backgroundSize: 'cover',
					}}>
					<div className='column'>
						<div className='column'>
							<h2 className='heading-2'>
								<i>Malasakit</i>
							</h2>
							<p className='subheading'>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor incididunt ut labore et dolore magna aliqua.
							</p>
							<p>
								<Button
									link='/our-business/inner'
									className='btn-bordered white'>
									Read More
								</Button>
							</p>
							<img
								src={`${basePath}/images/Homepage-1/Malasakit.png`}
								style={{}}
							/>
						</div>
					</div>
				</Section>

				<PageCTA />
			</Fade>
		</>
	);
}
