import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';

import Button from '@/components/button/button';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import useAnim from '@/hooks/use-anim';

import SingleParallax from '@/components/single-parallax/single-parallax';
import Link from 'next/link';

import gsap from 'gsap';
import { pageTranslate } from '@/hooks/pageAnim';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

export default function News() {
	const parent1 = useRef(null);
	const { scrollYProgress: scrollYProgress_start1 } = useScroll({
		target: parent1,
		offset: ['start end', 'end start'],
	});

	const news_section = useRef(null);

	const [modal, setModal] = useState({
		active: false,
		index: 0,
		link: '',
	});

	const newsItems = [
		{
			title:
				'SMC bests other PH firms; jumps to 43rd in Forbes’ World’s Best Employers list—after ranking high in Time’s World’s Best Companies',
			desc: 'Since 2013, in the aftermath of typhoons Sendong and Yolanda, San Miguel Corporation (SMC) has been at the forefront of building resilient housing communities nationwide.',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n1.png',
			link: '/news/inner',
		},
		{
			title:
				'SMC, Ayala ink agreement to integrate Arca South to Skyway Stage 4 project',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n2.png',
			link: '/news/inner',
		},
		{
			title: "SMC's nine-month profit more than doubles to ₱31.2 billion",
			date: 'November 28, 2023',
			img: '',
			link: '/news/inner',
		},
		{
			title:
				'SMB delivers solid nine-month results amidst higher volumes, improved market conditions',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n4.png',
			link: '/news/inner',
		},
		{
			title:
				'SMC, Pangasinan ink historic JVA for PLEX; to boost economy and connectivity in Central, Northern Luzon',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n5.png',
			link: '/news/inner',
		},
	];

	useEffect(() => {
		console.log(modal.index);
	}, [modal.index]);

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title='News' noBg={true} />

				<Section columnCount={2} containerStyle={{ alignItems: 'flex-start' }}>
					<div className='column news-column'>
						<div
							className='news-featured'
							ref={parent1}
							style={{ backgroundImage: `url(${newsItems[0].img})` }}>
							<div className='desc-container'>
								<div className='news-date small'>{newsItems[0].date}</div>
								<h2 className='heading-5 news-title'>{newsItems[0].title}</h2>
								{/* <p>{newsItems[0].desc}</p> */}
								<p>
									<Button link='/news/inner' className={'btn-bordered pri'}>
										Read More
									</Button>
								</p>
							</div>
						</div>
						<div className='news-list'>
							{newsItems.map((news, index) => {
								return (
									<NewsItem
										link={news.link}
										index={index}
										title={news.title}
										date={news.date}
										img={news.img}
										// setModal={setModal}
										key={`NewsItem_` + index}
									/>
								);
							})}
						</div>
					</div>
					<div className='column news-column'>
						<div className='other-news'>
							<h3 className='heading-4'>Other News</h3>
							{newsItems.map((news, index) => {
								return (
									<NewsItem
										link={news.link}
										index={index}
										title={news.title}
										date={news.date}
										img={news.img}
										// setModal={setModal}
										key={`NewsItem_` + index}
									/>
								);
							})}
						</div>
					</div>
				</Section>
			</Curve>
		</>
	);
}

export function NewsItem({ index, title, date, img, link, setModal }) {
	return (
		<div className='news-item'>
			<div className='img-container'>
				<Link href={link}>
					<img src={img} />
				</Link>
			</div>
			<div className='desc-container'>
				<div className='news-date'>
					<small className='small'>{date}</small>
				</div>
				<h3 className='news-title heading-6'>
					<Link href={link}>{title}</Link>
				</h3>
			</div>
		</div>
	);
}
