import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

import { BsArrowLeftCircle, BsArrowRightCircle } from 'react-icons/bs';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

export default function FoodAndBeverages() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title={'Other Businesses'} direction='center' />

				<Section
					columnCount={3}
					containerSize='medium'
					containerStyle={{ flexDirection: 'row-reverse' }}>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='https://aibc.com.ph/'>
								<img src={`${basePath}/images/OurBusinesses/ob-1.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='https://aibc.com.ph/'>
									Anchor Insurance Brokerage Corp
								</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href=''>
								<img src={`${basePath}/images/OurBusinesses/ob-2.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href=''>ARCHEN Technologies</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='https://www.bankcom.com.ph/'>
								<img src={`${basePath}/images/OurBusinesses/ob-3.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='https://www.bankcom.com.ph/'>Bank of Commerce</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href=''>
								<img src={`${basePath}/images/OurBusinesses/ob-4.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href=''>SMC Retirement Funds Office</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='https://smcstocktransfer.com.ph/'>
								<img src={`${basePath}/images/OurBusinesses/ob-5.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='https://smcstocktransfer.com.ph/'>
									SMC Stock Transfer Corp
								</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href=''>
								<img src={`${basePath}/images/OurBusinesses/ob-6.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href=''>SMITS, Inc.</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='https://www.prosync.com.ph/'>
								<img src={`${basePath}/images/OurBusinesses/ob-7.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='https://www.prosync.com.ph/'>ProSync</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='#'>
								<img src={`${basePath}/images/OurBusinesses/ob-8.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='#'>SMC Asia Car Distributors Corporation</a>
							</h3>
						</div>
					</div>
					<div class='column text-center'>
						<div class='img-container'>
							<a href='#'>
								<img src={`${basePath}/images/OurBusinesses/ob-9.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='#'>Velocita Motors, Inc. (VMI)</a>
							</h3>
						</div>
					</div>
					<div
						class='column text-center grow-limit'
						style={{
							marginLeft: 'auto',
							marginRight: 'auto',
						}}>
						<div class='img-container'>
							<a href='https://petrogen.com.ph/' target='_blank'>
								<img src={`${basePath}/images/OurBusinesses/ob-10.png`} />
							</a>
						</div>
						<div class='desc'>
							<h3 class='heading-5 card-title'>
								<a href='https://petrogen.com.ph/' target='_blank'>
									Petrogen Insurance Corporation
								</a>
							</h3>
						</div>
					</div>
				</Section>

				<Section sectionStyle={{ paddingTop: 0 }}>
					<motion.div className='page-controls'>
						<motion.div className='control prev'>
							<div className='img-container'>
								<img src={`${basePath}/images/OurBusinesses/thumb.png`} />
							</div>

							<div className='control-details'>
								<div className='arrow'>
									<BsArrowLeftCircle size={'1.75rem'} />
								</div>
								<div>
									<p>
										<b>Previous Business</b>
									</p>
									<p className='label heading-5'>San Miguel Foods</p>
								</div>
							</div>
						</motion.div>

						<motion.div className='control next'>
							<div className='img-container'>
								<img src={`${basePath}/images/OurBusinesses/thumb.png`} />
							</div>
							<div className='control-details'>
								<div className='arrow'>
									<BsArrowRightCircle size={'1.75rem'} />
								</div>
								<div>
									<p>
										<b>Next Business</b>
									</p>
									<p className='label heading-5'>San Miguel Foods</p>
								</div>
							</div>
						</motion.div>
					</motion.div>
				</Section>
			</Curve>
		</>
	);
}
