import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import { useScroll, useTransform } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';

import Link from 'next/link';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import Column from '@/cms-components/Column/column';
import StackedImages from '@/cms-components/StackedImages/stackedimages';

export default function OurBusinesses() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<meta
					http-equiv='Content-Security-Policy'
					content='frame-src youtube.com www.youtube.com'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Our Businesses'} direction='center' />
				<Section columnCount={2} containerStyle={{ alignItems: 'center' }}>
					<Column>
						<p>
							San Miguel Corporation is one of the largest and most diversified
							conglomerates in the Philippines by revenues and total assets,
							with sales equivalent to approximately 4% of the Philippine GDP in
							2020.
						</p>
						<p>
							SMC’s five key business groups, most of which are market leaders
							in their respective industries, include the following: food and
							beverage, packaging, fuel and oil, energy, and infrastructure. In
							addition, SMC has investments in other businesses such as property
							development and leasing, cement, car distributorship, and banking
							services.
						</p>
						<p>
							SMC has a portfolio of companies that is interwoven into the
							economic fabric of the Philippines, benefiting from, as well as
							contributing to, the development and economic progress of the
							nation.
						</p>
						<p>
							SMC, through its subsidiaries and affiliates, has become a market
							leader in its businesses in the Philippines with an extensive
							portfolio of products that include beer, spirits, non-alcoholic
							beverages, poultry, animal feeds, flour, fresh and processed
							meats, dairy products, coffee, various packaging products, and a
							full range of refined petroleum products, most of which are
							leaders in their respective markets. In addition, SMC contributes
							to the growth of downstream industries and sustains a network of
							hundreds of third-party suppliers.
						</p>
					</Column>
					<Column>
						<StackedImages
							images={[
								`${basePath}/images/CSR/EOP-1.svg`,
								``,
								`${basePath}/images/OurBusinesses-1.png`,
							]}
						/>
					</Column>
				</Section>

				<Section columnCount={2} containerStyle={{ rowGap: 0 }}>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
					<Column>
						<BusinessItem />
					</Column>
				</Section>
			</Fade>
		</>
	);
}

function BusinessItem() {
	return (
		<div className='business-item'>
			<div className='img-container'>
				<Link href='/our-business/inner'>
					<img src={`${basePath}/images/OurBusinesses/logo.png`}></img>
				</Link>
			</div>
			<div className='desc-container'>
				<div className='business-type small-text'>Food and Beverages</div>
				<h3 className='business-name heading-3'>
					<Link href='/our-business/inner'>San Miguel Foods</Link>
				</h3>
				<p>
					Our food company offers a wide range of quality food products. Home to
					many of the Philippines’ largest food brands, some of which are the
					most formidable brands in the domestic food industry.
				</p>
			</div>
		</div>
	);
}
