import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import VideoContent from '@/cms-components/VideoContent/Video';
import Section from '@/cms-components/Section/Section';
export default function OurValues() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Our Values'} direction='center' />
				<Section>
					<div className='column'>
						<VideoContent src={`${basePath}/videos/615559faf380d.mp4`} />
					</div>
				</Section>
				<Section>
					<div className='column text-content'>
						<h2 className='heading-2 split-color'>
							Malasakit is at the core <b>of who we are as a company</b>
						</h2>
						<h3 className='heading-5'>We do what is right</h3>
						<p>
							We believe in profit with honor. For us, this simply means doing
							what we’ll say we’ll do and acting with honesty, fairness and
							integrity.
						</p>

						<h3 className='heading-5'>We believe in doing our best</h3>
						<p>
							We will give every single person we touch the best we can offer.
							We are passionate about our brands, products and services.
						</p>

						<h3 className='heading-5'>
							We take accountability for our decisions
						</h3>
						<p>
							We hold ourselves accountable for delivering results, we keep to
							our commitments and we take responsibility for our actions.
						</p>

						<h3 className='heading-5'>We think innovation</h3>
						<p>
							Our innovation lends us agility and is driven by our understanding
							of what our customers and stakeholders need.
						</p>

						<h3 className='heading-5'>We help our people succeed</h3>
						<p>
							We believe in treating each other with respect. We cultivate a
							culture that recognizes the individuality and contributions of
							each of our employees, helping them to become productive and
							responsible members of society.
						</p>

						<h3 className='heading-5'>We are a good neighbor</h3>
						<p>
							We are a positive force in our communities. We believe in doing
							what is good for the greatest number of people.
						</p>

						<h3 className='heading-5'>We advocate sustainable development</h3>
						<p>
							We believe in using only what we need and integrating
							sustainability practices into our operations. Water stewardship,
							energy optimization and reducing waste are our key environmental
							priorities.
						</p>
					</div>
				</Section>
			</Fade>
		</>
	);
}
