import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import VideoContent from '@/cms-components/VideoContent/Video';
import Section from '@/cms-components/Section/Section';
export default function SMCPrivacy() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'SMC Privacy Statement'} direction='center' />

				<Section columnCount={3}>
					<div className='column text-content'>
						<p>Updated: 20 September 2017</p>
						<p>
							San Miguel Corporation and its subsidiaries{' '}
							<b>
								(&quot;SMC,&quot; &quot;We,&quot; &quot;us&quot; or
								&quot;our&quot;)
							</b>{' '}
							respect your privacy and will keep secure and confidential all
							personal and sensitive information that you may provide to SMC,
							and/or those that SMC may collect from you{' '}
							<b>(&quot;Personal Data&quot;)</b>.{' '}
						</p>
						<p>
							This privacy statement <b>(&quot;Statement&quot;)</b> provides for
							the Personal Data we obtain, or which you may provide through this
							website, <a href='../../../'>www.sanmiguel.com.ph</a>
							<b>(&quot;Website&quot;)</b>, and the standards we observe in
							using, processing, keeping, securing, and disclosing said Personal
							Data.
						</p>
						<p>
							{' '}
							Please read this Statement carefully to understand how We treat
							Personal Data. We may update this Statement from time to time to
							reflect change (s) in the law and/or our internal standards. When
							We do so, We will notify you by posting the updated Statement in
							this Website for your information and reference. By accessing the
							Website and submitting your Concerns (defined below), or Personal
							Data through it, you expressly acknowledge that you have read,
							understood and hereby agree to all of the terms of this Statement
							and that you provide consent for us to:{' '}
						</p>
						<ul>
							<li>
								Process your Personal Data, as provided under applicable laws,
								regulations, and our policies, for our subsidiaries and
								affiliates, contractors, service providers, and other authorized
								third parties&apos; legitimate purpose/s;
							</li>
							<li>
								{' '}
								Make your Personal Data available for our subsidiaries and
								affiliates, contractors, service providers, and other third
								parties.{' '}
							</li>
						</ul>
						<p>
							<b>
								<i>Personal Data We Collect and Process</i>
							</b>
						</p>
						<p>
							{' '}
							Our Website allows you to directly reach us and provide comments,
							suggestions and complaints (collectively,{' '}
							<b>&quot;Concerns&quot;</b>) on our products and services to help
							us improve them. When you access our Website and submit your
							Concerns, We ask you to provide the following Personal Data to
							identify you, and enable SMC to act on your Concerns:{' '}
						</p>
						<ul>
							<li>Full Name</li>
							<li>E-mail address</li>
							<li>Contact number</li>
						</ul>
						<p>
							If you do not provide any or all of the foregoing Personal Data
							accurately, We may not be in the position to effectively address
							your Concerns.
						</p>
						<p>
							Any additional Personal Data that you may provide through your
							correspondence(s) with SMC in connection with your Concerns shall
							also be considered and treated as Personal Data.
						</p>
						<p>
							When you navigate through and interact with the Website, depending
							on your settings, We may use automatic data collection
							technologies (e.g., cookies, web beacons, small data text files or
							similar technologies) to obtain certain information about your
							equipment, browsing actions, and patterns, such as:
						</p>
						<ul>
							<li>
								Details of your visits to the Website (e.g., traffic data,
								location data, logs, and other communication data, and the
								resources that you access and use on the Website).
							</li>
							<li>
								Information about your computer/device and internet connection,
								as well as IP address, operating system, and browser type
								(collectively, <b>&quot;Collected Data&quot;</b>).{' '}
							</li>
						</ul>
						<p>
							The Collected Data are mostly statistical data but may include
							other Personal Data, and We may maintain or associate them with
							the Personal Data that We ask you to provide to SMC in connection
							with your Concerns.
						</p>
						<p>
							<b>
								<i> What We Do with Personal Data and Collected Data </i>
							</b>
						</p>
						<p>
							Upon receiving your Concerns and the accompanying Personal Data
							identifying you, SMC or its duly authorized third party forwards
							the same to the concerned SMC department. SMC may use your
							Personal Data to get in touch with you, in order to attend to,
							further inquire about, and address your Concerns. SMC may
							separately contact you to confirm that the concerned SMC
							department has acted on your Concerns, ask you for further
							feedback, request your participation in surveys and/or provide
							information on its products and services.
						</p>
						<p>
							For the Collected Data, We use them to help us improve our Website
							and to deliver a better and more personalized service by enabling
							us to:
						</p>
						<ul>
							<li>Estimate our audience size and usage patterns;</li>
							<li>
								Store information about your preferences, allowing us to
								customize our Website according to your individual interests;
							</li>
							<li>Speed up your searches; and</li>
							<li>Recognize you when you return to our Website.</li>
						</ul>
						<p>
							<b>
								<i> Retention of Personal Data and Collected Data </i>
							</b>
						</p>
						<p>
							SMC and/or its duly authorized third party shall retain the
							Personal Data and Collected Data for a maximum period of five (5)
							years counted from the date you provide it to SMC, or when they
							were collected, respectively.
						</p>
						<p>
							<b>
								<i>
									Disclosure and Sharing of Personal Data and Collected Data
								</i>
							</b>
						</p>
						<p>
							We may disclose aggregated information about our users, and
							information that does not identify, or when combined with other
							information, does not directly and certainly identify any
							individual, without restriction.
						</p>
						<p>
							We may disclose and share the Personal Data and Collected Data,
							subject to compliance with applicable laws and regulations, on a
							need to know basis, and in all cases only for legitimate business
							purposes, as follows:
						</p>
						<ul>
							<li>To our subsidiaries and affiliates;</li>
							<li>
								To contractors, service providers, and other third parties We
								engage to support our business, and who are bound by contractual
								obligations to keep Customer Information and Collected Data
								confidential, and use it only for the purposes for which We
								disclose it to them;
							</li>
							<li>
								To government and law enforcement agencies and regulatory
								bodies;
							</li>
							<li>
								To comply with orders of courts, government agencies, regulatory
								bodies, stock exchanges and with applicable laws and
								regulations;
							</li>
							<li>
								{' '}
								If We believe disclosure is necessary or appropriate to protect
								the rights, property, or safety of SMC, our subsidiaries and
								affiliates, officers, employees customers, or other third
								parties;{' '}
							</li>
							<li>
								To a buyer or other successor in the event of a merger,
								divestiture, restructuring, reorganization, dissolution, or
								other sale or transfer of some or all of SMC’s assets, whether
								as a going concern or as part of bankruptcy, liquidation, or
								similar proceeding, in which Personal Data held by SMC about our
								Website users is among the assets transferred; and
							</li>
							<li>
								To conduct investigations of breaches of SMC’s internal
								policies, laws and regulations, enforce appropriate sanctions
								and pursue legal actions if necessary.
							</li>
						</ul>
						<p>
							<b>
								<u> Website Visitor Under the Age of 18 </u>
							</b>
						</p>
						<p>
							No one under age eighteen (18) ( <b>&quot;Minors&quot;</b>) may
							provide any Personal Data on the Website. SMC does not knowingly
							collect Personal Data from Minors. If you are a Minor, please do
							not use or provide any information on this Website about yourself.{' '}
						</p>
						<p>
							<b>
								<u>
									Third-Party Use of Cookies and Other Tracking Technologies
								</u>
							</b>
						</p>
						<p>
							{' '}
							Some content or applications, including advertisements, on the
							Website are served by third-parties, including advertisers, ad
							networks and servers, content providers, and application
							providers. These third parties may use cookies (alone or in
							conjunction with web beacons or other tracking technologies) to
							collect information about you when you use our Website. The
							information they collect may be associated with your Personal Data
							or they may collect information, including Personal Data, about
							your online activities over time and across different websites and
							other online services. They may use this information to provide
							you with interest-based (behavioral) advertising or other targeted
							content.{' '}
						</p>
						<p>
							We do not control these third parties&apos; tracking technologies
							or how they may be used. If you have any questions about an
							advertisement or other targeted content, you should contact the
							responsible provider directly.
						</p>

						<div
							style={{
								float: 'right',
								maxWidth: '100%',
							}}>
							<img
								src={`${basePath}/images/dpo.webp`}
								alt=''
								height='375'
								width='580'
							/>
						</div>
						<p>
							<b>
								<u>Accessing and Correcting Your Personal Data</u>
							</b>
						</p>
						<p>
							You are entitled to certain rights in relation to the Personal
							Data collected from you, including the right to access and correct
							your Personal Data being processed, object to the processing, and
							to lodge a complaint before the National Privacy Commission in
							case of violation of your rights as data subject.{' '}
						</p>
						<p>
							You may send us an e-mail at customercare@sanmiguel.com.ph to
							request access to, correct and/or delete any Personal Data that
							you have provided to us. Please be advised, however, that We
							cannot delete your Personal Data without restricting or removing
							our ability to effectively address your Concerns. We may not
							accommodate a request to correct and/or delete Personal Data if We
							believe the same would violate any law or legal requirement or
							cause the Personal Data to be incorrect.
						</p>
						<p>
							<b>
								<u>Security of your Personal Data and the Collected Data</u>
							</b>
						</p>
						<p>
							We have implemented technical, organizational, and physical
							measures designed to protect the confidentiality, integrity, and
							availability of your Personal Data and Collected Data and secure
							such Data from destruction, unauthorized access, alteration,
							disclosure, fraudulent misuse and/or any other unlawful
							processing, as well as other natural and human dangers.
						</p>
						<p>
							<b>
								<u>Contact Information</u>
							</b>
						</p>
						<p>
							Should you have any questions and/or concerns regarding this
							Statement, SMC’s use of your Personal Data and the Collected Data,
							or your rights in relation thereto under the Data Privacy Act of
							2012, please do not hesitate to contact the SMC Data Protection
							Officer at the following:{' '}
							<a href='mailto:dpo@sanmiguel.com.ph'>dpo@sanmiguel.com.ph</a> and
							(+632) 632-3007.{' '}
						</p>
					</div>
				</Section>
			</Fade>
		</>
	);
}
