import Head from 'next/head';
import Curve from '@/components/Layout/Curve';
import Parallax from '@/components/Parallax/parallax';
import SampleVideo from '@/components/SampleVideo/sample-video';
import OurBusinesses from '@/cms-components/OurBusinesses/OurBusinesses';

import {
	animate,
	motion,
	useScroll,
	useSpring,
	useTransform,
} from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';
import Card from '@/components/card/card';
import Button from '@/components/button/button';
import PageCTA from '@/cms-components/PageCTA/PageCTA';
import PageTitle from '@/cms-components/PageTitle/PageTitle';
import div from '@/components/single-parallax/single-parallax';
import { useDimensions } from '@/hooks/use-dimension';
import useAnim from '@/hooks/use-anim';
import { pageTranslate } from '@/hooks/pageAnim';
import TextGradient from '@/cms-components/TextGradient/TextGradient';
import SingleParallax from '@/components/single-parallax/single-parallax';
import Image from 'next/image';
import ParallaxGrid from '@/cms-components/ParallaxGrid/ParallaxGrid';
import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';
import { BsArrowLeftCircle, BsArrowRightCircle } from 'react-icons/bs';
import { Link } from 'lucide-react';

import { basePath } from '@/hooks/use-basepath';

export default function OurBusinessesInner() {
	const parallaxColumn = useRef(null);
	const [dimension, setDimension] = useState({ width: 0, height: 0 });

	const { scrollYProgress } = useScroll({
		target: parallaxColumn,
		offset: ['start end', 'end start'],
	});

	const section2 = useRef(null);
	const { scrollYProgress: section_2_scroll } = useScroll({
		target: section2,
		offset: ['start end', 'end start'],
	});

	const { height } = dimension;

	const y1 = useTransform(scrollYProgress, [0, 1], [0, height * 2]);

	const y2 = useTransform(scrollYProgress, [0, 1], [0, height * 3.3]);

	const y3 = useTransform(scrollYProgress, [0, 1], [0, height * 1.25]);

	const y4 = useTransform(scrollYProgress, [0, 1], [0, height * 3]);

	useEffect(() => {
		var base_url = window.location.origin;
		console.log(base_url);

		const resize = () => {
			setDimension({ width: window.innerWidth, height: window.innerHeight });
		};

		window.addEventListener('resize', resize);

		resize();

		return () => {
			window.removeEventListener('resize', resize);
		};
	}, []);

	const variants = {
		initial: {
			opacity: 0,
		},
		visible: {
			opacity: 1,
		},
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageTitle
					title='Ginebra '
					split='San Miguel Inc.'
					horizontal='center'
				/>

				<FullPageBanner>
					<img src={`${basePath}/images/OurBusinesses/1111.png`} />
				</FullPageBanner>

				<div
					className='section-content img-section no-min-height'
					{...useAnim(pageTranslate(2))}
					ref={section2}>
					<div className='container-fluid-width small'>
						<div className='business-inner'>
							<div className='desc-container'>
								<p className='heading-4 split-color'>
									<b>
										Ginebra San Miguel, Inc. is the world’s largest gin producer
										by volume
									</b>{' '}
									as well as the market leader in the domestic hard liquor
									market,
								</p>

								<p>
									SMC has a portfolio of companies that is interwoven into the
									economic fabric of the Philippines, benefiting from, as well
									as contributing to, the development and economic progress of
									the nation.
								</p>

								<p>
									SMC, through its subsidiaries and affiliates, has become a
									market leader in its businesses in the Philippines with an
									extensive portfolio of products that include beer, spirits,
									non-alcoholic beverages, poultry, animal feeds, flour, fresh
									and processed meats, dairy products, coffee, various packaging
									products, and a full range of refined petroleum products, most
									of which are leaders in their respective markets. In addition,
									SMC contributes to the growth of downstream industries and
									sustains a network of hundreds of third-party suppliers.
								</p>
							</div>
							<div className='desc-container other-details'>
								<h3 className='heading-6'>Business Opportunities</h3>
								<div>
									<p>Ginebra San Miguel, Inc.</p>
									<p className='small'>
										Corporate Head Office 3rd, 5th & 6th
										<br />
										Floor, San Miguel Properties Centre, St. <br />
										Francis Street, Mandaluyong City 1550
									</p>
									<p>Customer Care</p>
									<p className='small'>
										For inquiries, orders and suggestions on our products and
										services,
										<br />
										Tel no.: (632) 8632-2564
										<br />
										Fax no.: (632) 8632-3299
										<br />
										Mailbox No.: 2623
										<br />
									</p>
									<p>Email and Social Media</p>
									<p className='small'>customercare.gsmi@smg.sanmiguel</p>
								</div>
								<div></div>
							</div>
						</div>
					</div>
				</div>
				<motion.div
					className='section-content business-controls'
					initial='initial'
					whileInView='visible'
					viewport={{
						once: 'true',
						amount: 'all',
					}}>
					<div className='controls'>
						<motion.div className='control prev' variants={variants}>
							<div className='arrow'>
								<BsArrowLeftCircle size={'1.25rem'} />
								Previous
							</div>
							<div className='control-details'>
								<p className='label heading-5'>San Miguel Foods</p>
								<div className='img-container'>
									<img src={`${basePath}/images/OurBusinesses/thumb.png`} />
								</div>
							</div>
						</motion.div>

						<motion.div className='control next' variants={variants}>
							<div className='arrow'>
								Next
								<BsArrowRightCircle size={'1.25rem'} />
							</div>
							<div className='control-details'>
								<p className='label heading-5'>San Miguel Foods</p>
								<div className='img-container'>
									<img src={`${basePath}/images/OurBusinesses/thumb.png`} />
								</div>
							</div>
						</motion.div>
					</div>
				</motion.div>
			</Curve>
		</>
	);
}
