import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

import { BsArrowLeftCircle, BsArrowRightCircle } from 'react-icons/bs';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import { NextBusinesses, PrevBusinesses } from '../our-businesses/inner';
import Column from '@/cms-components/Column/column';

export default function FoodAndBeverages() {
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner title={'Cement Business'} direction='center' />

				<Section
					columnCount={2}
					containerSize='medium'
					containerStyle={{ flexDirection: 'row-reverse' }}>
					<div className='column bussinesses-desc-column'>
						<Column>
							<p className='heading-5'>
								The cement business is conducted through San Miguel Equity
								Investments Inc. (SMEII), which is wholly owned by SMC.
							</p>
						</Column>
						<Column>
							<p>
								SMEII is a holding company which owns 100% of the issued and
								outstanding common stock of Northern Cement Corporation (NCC),
								100% of Southern Concrete Industries Inc. (SCII), and 99.96% of
								the newly acquired Eagle Cement Corporation (Eagle).
							</p>
						</Column>
						<Column>
							<p>
								The cement business owns and operates fully-integrated cement
								production facilities in Barangay Labayug, Sison, Province of
								Pangasinan (NCC) and in Barangay Akle, San Ildefonso, Province
								of Bulacan (Eagle), a cement grinding plant in Barangay Darong,
								Santa Cruz, Province of Davao Del Sur (SCII), and limestone,
								shale and pozzolan quarries in Pangasinan and Bulacan (NCC and
								Eagle). As a whole, the cement business has a total annual rated
								cement production capacity of approximately 17.5 million MTPY of
								finished cement.
							</p>
						</Column>
					</div>
				</Section>

				<Section sectionStyle={{ paddingTop: 0 }}>
					<motion.div className='page-controls'>
						<PrevBusinesses />
						<NextBusinesses />
					</motion.div>
				</Section>
			</Fade>
		</>
	);
}
