import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { getColors } from '@/hooks/use-color';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

export default function InvestorContact() {
	const { gray2, red } = getColors;

	const icon = {
		size: '1rem',
	};
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Curve>
				<PageBanner title={'Investor Contact'} direction={'center'} />

				<Section columnCount={2} containerStyle={{ alignItems: 'center' }}>
					<div className='column'>
						<div className='image-content stacked'>
							<div className='img-container'>
								<img
									src={`${basePath}/images/InvestorContact/InvestorContact-1.svg`}
								/>
							</div>
							<div className='img-container'>
								<img src={`${basePath}/images/ph.svg`} />
							</div>
							<div className='img-container'>
								<img
									src={`${basePath}/images/InvestorContact/InvestorContact-2.png`}
								/>
							</div>
						</div>
					</div>
					<div className='column'>
						<div className='text-content'>
							<h2 className='heading-5'>
								<b>
									For institutional investor inquiries, please write or call:
								</b>
							</h2>
							<p>
								Investor Relations
								<br />
								<b>Reynabeth D. De Guzman</b>
								<br />
								Investor Relations Head
								<br />
								San Miguel Corporation
								<br />
								Telephone: (+632) 8-632-3752
								<br />
								E-mail: 
								<a href='mailto: SMCInvestorRelations@sanmiguel.com.ph'>
									SMCInvestorRelations@sanmiguel.com.ph
								</a>
							</p>
						</div>
					</div>
				</Section>
			</Curve>
		</>
	);
}
