import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion } from 'framer-motion';

import { getColors } from '@/hooks/use-color';

import Link from 'next/link';

import { ImFacebook, ImLinkedin2, ImSphere, ImYoutube } from 'react-icons/im';
import { LuInstagram } from 'react-icons/lu';

import {
	Box,
	Accordion,
	AccordionItem,
	AccordionButton,
	AccordionPanel,
	AccordionIcon,
	AspectRatio,
} from '@chakra-ui/react';
import PageTitle from '@/cms-components/PageTitle/PageTitle';
import ColumnSection from '@/cms-components/ColumnSection/ColumnSection';
import TextGradient from '@/cms-components/TextGradient/TextGradient';
import useAnim from '@/hooks/use-anim';
import { pageTranslate } from '@/hooks/pageAnim';
import FloatingImages from '@/cms-components/FloatingImages/floatingimages';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';

export default function InvestorContact() {
	const { gray2, red } = getColors;

	const icon = {
		size: '1rem',
	};
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Curve>
				<PageBanner title={'Investor Contact'} direction={'center'} />

				<Section columnCount={2}>
					<div className='column'>
						<div className='image-content'>
							<div className='img-container'>
								<img src={`${basePath}/images/OurCompany/Our-Company.png`} />
							</div>
						</div>
					</div>
					<div className='column'>
						<div className='text-content'>
							<h2 className='heading-5'>
								<b>
									For institutional investor inquiries, please write or call:
								</b>
							</h2>
							<p>
								Investor Relations
								<br />
								<b>Reynabeth D. De Guzman</b>
								<br />
								Investor Relations Head
								<br />
								San Miguel Corporation
								<br />
								Telephone: (+632) 8-632-3752
								<br />
								E-mail: 
								<a href='mailto: SMCInvestorRelations@sanmiguel.com.ph'>
									SMCInvestorRelations@sanmiguel.com.ph
								</a>
							</p>
						</div>
					</div>
				</Section>
			</Curve>
		</>
	);
}
