import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll } from 'framer-motion';
import { useRef } from 'react';

import Button from '@/components/button/button';

import Link from 'next/link';

import { AspectRatio, Badge, Flex } from '@chakra-ui/layout';

import { basePath } from '@/hooks/use-basepath';

import Section from '@/cms-components/Section/Section';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import { NewsItem } from '../news';

export default function Kaunlaran() {
	const kol = useRef(null);
	const { scrollYprogress } = useScroll({
		target: kol,
		offset: ['start end', 'end start'],
	});

	const kaunlaran_items = [
		{
			link: '/',
			img: basePath + '/images/News/n1.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			desc: 'Non dapibus eget dictum congue neque nibh. Feugiat sapien cras felis tristique morbi sit sit vel. Dolor neque morbi tortor sit tincidunt semper.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n2.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n3.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n4.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/News/n5.png',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
	];
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title={'Kaunlaran Online'} noBg={true} />

				<Section columnCount={3}>
					<div className='column' style={{ flex: '1 1 60rem' }}>
						<div className='news-featured column'>
							<div className='img-container'>
								<img src={`${kaunlaran_items[0].img}`} />
							</div>
							<div className='desc-container'>
								<div className='news-date small-text'>
									{kaunlaran_items[0].date}
								</div>
								<h2 className='heading-3 news-title'>
									{kaunlaran_items[0].title}
								</h2>
								<p>{kaunlaran_items[0].desc}</p>
								<p>
									<Button link='/news/inner' className={'btn-bordered pri'}>
										Read More
									</Button>
								</p>
							</div>
						</div>
					</div>
					{kaunlaran_items.map((news, index) => {
						return (
							<div className='column grow-limit' key={`NewsItem_` + index}>
								<NewsItem
									link={news.link}
									index={index}
									title={news.title}
									date={news.date}
									img={news.img}
									direction={'horizontal'}
								/>
							</div>
						);
					})}
				</Section>
			</Curve>
		</>
	);
}
