import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll } from 'framer-motion';
import { useRef } from 'react';

import Button from '@/components/button/button';

import Link from 'next/link';

import { AspectRatio, Badge, Flex } from '@chakra-ui/layout';

import { basePath } from '@/hooks/use-basepath';
import { NewsItem } from '@/pages/news';
import Section from '@/cms-components/Section/Section';
import PageBanner from '@/cms-components/PageBanner/PageBanner';

export default function Kaunlaran() {
	const kol = useRef(null);
	const { scrollYprogress } = useScroll({
		target: kol,
		offset: ['start end', 'end start'],
	});

	const kaunlaran_items = [
		{
			link: '/',
			img: basePath + '/images/CSR/www-1.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			desc: 'Non dapibus eget dictum congue neque nibh. Feugiat sapien cras felis tristique morbi sit sit vel. Dolor neque morbi tortor sit tincidunt semper.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-2.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-3.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-4.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-5.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-6.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-7.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-8.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-9.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-10.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-11.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
		{
			link: '/',
			img: basePath + '/images/CSR/www-12.jpg',
			title: 'Sit porttitor pellentesque fermentum leo ipsum lacus.',
			date: 'Jan-Mar 2023',
			vol: 'Vol. 55 Issue 1',
		},
	];
	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title={'Kaunlaran'} noBg={true} />

				<Section columnCount={3}>
					<div className='column' style={{ flex: '1 1 60rem' }}>
						<div className='news-featured column'>
							<div className='img-container'>
								<img src={`${kaunlaran_items[0].img}`} />
							</div>
							<div className='desc-container'>
								<div className='news-date small'>{kaunlaran_items[0].date}</div>
								<h2 className='heading-5 news-title'>
									{kaunlaran_items[0].title}
								</h2>
								<p>{kaunlaran_items[0].desc}</p>
								<p>
									<Button link='/news/inner' className={'btn-bordered pri'}>
										Read More
									</Button>
								</p>
							</div>
						</div>
					</div>
					{kaunlaran_items.map((news, index) => {
						return (
							<div className='column' key={`NewsItem_` + index}>
								<NewsItem
									link={news.link}
									index={index}
									title={news.title}
									date={news.date}
									img={news.img}
									direction={'horizontal'}
								/>
							</div>
						);
					})}
				</Section>
			</Curve>
		</>
	);
}

function KaunlaranItems({ index, title, date, vol, img, link, setModal }) {
	return (
		<div className='issue-item'>
			<div className='img-container'>
				<Link href={link}>
					<AspectRatio ratio={1}>
						<img src={img} />
					</AspectRatio>
				</Link>
			</div>
			<div className='desc-container'>
				<h3 className='issue-title heading-6'>
					<Link href={link}>{title}</Link>
				</h3>
				<Flex justify={'space-between'} align={'center'}>
					<div className='issue-date small'>{date}</div>
					<div className='issue-vol small'>{vol}</div>
				</Flex>
			</div>
		</div>
	);
}
