import Head from 'next/head';
import Curve from '@/components/Layout/Curve';

import { motion, useScroll } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { getColors } from '@/hooks/use-color';

import Button from '@/components/button/button';

import PageTitle from '@/cms-components/PageTitle/PageTitle';

import useAnim from '@/hooks/use-anim';

import Link from 'next/link';

import gsap from 'gsap';
import { pageTranslate } from '@/hooks/pageAnim';
import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';
import FloatingImages from '@/cms-components/FloatingImages/floatingimages';

import { basePath } from '@/hooks/use-basepath';
import SingleParallax from '@/components/single-parallax/single-parallax';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import { NewsItem } from '@/pages/news';
import { Flex } from '@chakra-ui/layout';
import { FormControl, FormLabel, Input, Select } from '@chakra-ui/react';
import ImageSlider from '@/cms-components/ImageSlider/ImageSlider';

export default function AnnualReports() {
	const parent1 = useRef(null);
	const { scrollYProgress: scrollYProgress_start1 } = useScroll({
		target: parent1,
		offset: ['start end', 'end start'],
	});

	const news_section = useRef(null);

	const [modal, setModal] = useState({
		active: false,
		index: 0,
		link: '',
	});

	const newsItems = [
		{
			title: '2022 SMC Annual Reports',
			desc: 'With the COVID-19 pandemic in retreat, the Philippine economy is back on track. At San Miguel, our highest-ever revenues in 2022 reflect continuously growing demand for our products and services. Yet significant headwinds persist. Food insecurity, the power crisis, high prices of goods, and lack of opportunity remain major challenges for many Filipinos. ',
			date: 'November 28, 2023',
			img: basePath + '/images/AnnualReports.png',
			link: '/news/inner',
		},
		{
			title: '2022 SMC Annual Reports',
			desc: 'With the COVID-19 pandemic in retreat, the Philippine economy is back on track. At San Miguel, our highest-ever revenues in 2022 reflect continuously growing demand for our products and services. Yet significant headwinds persist. Food insecurity, the power crisis, high prices of goods, and lack of opportunity remain major challenges for many Filipinos. ',
			date: 'November 28, 2023',
			img: basePath + '/images/AnnualReports.png',
			link: '/news/inner',
		},
		{
			title: '2022 SMC Annual Reports',
			desc: 'With the COVID-19 pandemic in retreat, the Philippine economy is back on track. At San Miguel, our highest-ever revenues in 2022 reflect continuously growing demand for our products and services. Yet significant headwinds persist. Food insecurity, the power crisis, high prices of goods, and lack of opportunity remain major challenges for many Filipinos. ',
			date: 'November 28, 2023',
			img: basePath + '/images/AnnualReports.png',
			link: '/news/inner',
		},
	];

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Curve>
				<PageBanner title={'Annual Reports'} direction='center' />
				<Section>
					<Flex gap={5} mb={10}>
						<FormLabel>Select a year for quick search</FormLabel>
						<FormControl w={'auto'}>
							<Select placeholder='Select Year'>
								<option>United Arab Emirates</option>
								<option>Nigeria</option>
							</Select>
						</FormControl>
					</Flex>
					<ImageSlider captionPosition='annual-report' gradient='partial' />
				</Section>
			</Curve>
		</>
	);
}
