import Head from 'next/head';
import Fade from '@/components/Layout/Fade';

import { motion } from 'framer-motion';

import Button from '@/components/button/button';

import FullPageBanner from '@/cms-components/FullPageBanner/fullpagebanner';

import { basePath } from '@/hooks/use-basepath';
import PageBanner from '@/cms-components/PageBanner/PageBanner';
import Section from '@/cms-components/Section/Section';
import { NewsItem } from '@/pages/corporate/news';
import Column from '@/cms-components/Column/column';
import StackedImages from '@/cms-components/StackedImages/stackedimages';

export default function CSR() {
	const images = [
		`${basePath}/images/CSR/www-1.jpg`,
		`${basePath}/images/CSR/www-2.jpg`,
		`${basePath}/images/CSR/www-3.jpg`,

		`${basePath}/images/CSR/www-4.jpg`,
		`${basePath}/images/CSR/www-5.jpg`,
		`${basePath}/images/CSR/www-6.jpg`,

		`${basePath}/images/CSR/www-7.jpg`,
		`${basePath}/images/CSR/www-8.jpg`,
		`${basePath}/images/CSR/www-9.jpg`,

		`${basePath}/images/CSR/www-10.jpg`,
		`${basePath}/images/CSR/www-11.jpg`,
		`${basePath}/images/CSR/www-12.jpg`,
	];

	const newsItems = [
		{
			title:
				'SMC bests other PH firms; jumps to 43rd in Forbes’ World’s Best Employers list—after ranking high in Time’s World’s Best Companies',
			desc: 'Since 2013, in the aftermath of typhoons Sendong and Yolanda, San Miguel Corporation (SMC) has been at the forefront of building resilient housing communities nationwide.',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n1.png',
			link: '/news/inner',
		},
		{
			title:
				'SMC, Ayala ink agreement to integrate Arca South to Skyway Stage 4 project',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n2.png',
			link: '/news/inner',
		},
		{
			title:
				'SMB delivers solid nine-month results amidst higher volumes, improved market conditions',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n4.png',
			link: '/news/inner',
		},
		{
			title:
				'SMC, Pangasinan ink historic JVA for PLEX; to boost economy and connectivity in Central, Northern Luzon',
			date: 'November 28, 2023',
			img: basePath + '/images/News/n5.png',
			link: '/news/inner',
		},
	];

	return (
		<>
			<Head>
				<title>San Miguel Corporation</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
				/>
				<meta
					http-equiv='Content-Security-Policy'
					content='frame-src youtube.com www.youtube.com'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Fade>
				<PageBanner
					title={'Corporate Social Responsibility'}
					direction='center'
				/>

				<Section columnCount={2}>
					<Column>
						<div className='image-content'>
							<div className='img-container'>
								<img src={`${basePath}/images/CSR/CSR-1.png`} />
							</div>
						</div>
					</Column>
					<Column>
						<h2 className='heading-2'>
							More than a slogan, it’s a calling to our better selves. It’s a
							credo rooted in hope and action.
						</h2>
						<p>
							As a company, San Miguel Corporation invests in social projects
							not only because it makes good business sense, but because we
							believe the private sector needs to do its part. If the cities and
							communities we serve are thriving, San Miguel will thrive too.
						</p>
						<p>
							<Button
								link='/our-business/inner'
								className='pri-btn btn-bordered'>
								Learn More
							</Button>
						</p>
					</Column>
				</Section>

				<FullPageBanner
					image={`${basePath}/images/CSR/WWW.png`}
					caption={'The world we want'}></FullPageBanner>

				<Section columnCount={2} containerStyle={{ alignItems: 'center' }}>
					<Column>
						<h2 className='heading-2'>Environmental and Other Programs</h2>
						<p>
							The environmental program of San Miguel Foundation Inc. covers the
							protection of land, water, and air. On a smaller scale, the
							Foundation conducts tree-planting projects on areas identified by
							different San Miguel Corporation (SMC) plants. Tree-planting
							projects are usually scheduled to coincide with plant
							celebrations.
						</p>
						<p>
							The Foundation advocates the protection of coastal waters through
							its Coastal Resource Management, which engages in mangrove
							reforestation, artificial reef installation and regeneration of
							marine resources. Training on waste management and donation of
							trash bins through plant facilities are also conducted.
						</p>
						<p>
							<Button
								link='/our-business/inner'
								className='pri-btn btn-bordered'>
								Learn More
							</Button>
						</p>
					</Column>
					<Column>
						<StackedImages
							images={[
								`${basePath}/images/CSR/EOP-1.svg`,
								`${basePath}/images/ph.svg`,
								`${basePath}/images/CSR/EOP-2.png`,
							]}
						/>
					</Column>
				</Section>

				<Section columnCount={2} containerStyle={{ rowGap: 0 }}>
					<div className='column' style={{ flex: '1 0 100%' }}>
						<h3 className='heading-3'>
							Pellentesque cras tortor viverra dui tempor semper cum sed.
						</h3>
					</div>
					{newsItems.map((news, index) => {
						return (
							<Column key={`NewsItem_` + index}>
								<NewsItem
									link={news.link}
									index={index}
									title={news.title}
									date={news.date}
									img={news.img}
								/>
							</Column>
						);
					})}
				</Section>
			</Fade>
		</>
	);
}
